import type { Tarea } from "./types"

export const tareasIniciales: Tarea[] = [
  {
    id: "1",
    nombre: "Actualización plan de emergencia El Avellano",
    descripcion: "Revisión y actualización del plan de respuesta a emergencias para la estación El Avellano",
    areas: ["Seguridad"],
    estado: "En curso",
    fechaInicio: "2026-01-01",
    fechaFin: "2026-01-31",
    diasEjecutar: 30,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Operaciones", "Medio Ambiente"],
    documentos: [
      { nombre: "Plan_Emergencia_v2.pdf", url: "#" },
      { nombre: "Matriz_Riesgos.xlsx", url: "#" },
    ],
    actividades: [
      { id: "a1", nombre: "Emisión y capacitación al personal", porcentaje: 100, completada: true },
      { id: "a2", nombre: "Revisión comentarios plan emergencia PRS", porcentaje: 100, completada: true },
      { id: "a3", nombre: "Diseño y envío proveedor", porcentaje: 0, completada: false },
    ],
    avanceTotal: 67,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-15",
  },
  {
    id: "2",
    nombre: "Cambio Señalética TRM",
    descripcion: "Instalación de nueva señalética de seguridad en Terminal Marítimo",
    areas: ["Seguridad"],
    estado: "Atrasado",
    fechaInicio: "2025-12-01",
    fechaFin: "2025-12-31",
    diasEjecutar: 30,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Diseño_Señaletica.pdf", url: "#" }],
    actividades: [
      { id: "a4", nombre: "Diseño aprobado", porcentaje: 100, completada: true },
      { id: "a5", nombre: "Fabricación señalética", porcentaje: 100, completada: true },
      { id: "a6", nombre: "Instalación en campo", porcentaje: 0, completada: false },
    ],
    avanceTotal: 67,
    creadoPor: "Admin",
    fechaCreacion: "2025-11-15",
  },
  {
    id: "3",
    nombre: "Auditoría ambiental Q1 2026",
    descripcion: "Auditoría ambiental programada para el primer trimestre",
    areas: ["Medio Ambiente"],
    estado: "Planificado",
    fechaInicio: "2026-02-01",
    fechaFin: "2026-02-28",
    diasEjecutar: 28,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Legal", "Operaciones"],
    documentos: [],
    actividades: [
      { id: "a7", nombre: "Preparación documentación", porcentaje: 0, completada: false },
      { id: "a8", nombre: "Inspección en campo", porcentaje: 0, completada: false },
      { id: "a9", nombre: "Elaboración informe", porcentaje: 0, completada: false },
    ],
    avanceTotal: 0,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-20",
  },
  {
    id: "4",
    nombre: "Capacitación brigada de emergencias",
    descripcion: "Entrenamiento anual de brigadas de emergencia y primeros auxilios",
    areas: ["Seguridad", "Operaciones"],
    estado: "Finalizado",
    fechaInicio: "2025-11-01",
    fechaFin: "2025-11-30",
    diasEjecutar: 30,
    prioridad: "Alta",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Programa_Capacitacion.pdf", url: "#" }],
    actividades: [
      { id: "a10", nombre: "Planificación de sesiones", porcentaje: 100, completada: true },
      { id: "a11", nombre: "Ejecución capacitaciones", porcentaje: 100, completada: true },
      { id: "a12", nombre: "Evaluación participantes", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-10-15",
  },
  {
    id: "5",
    nombre: "Revisión contratos proveedores",
    descripcion: "Revisión y renovación de contratos con proveedores críticos",
    areas: ["Legal", "Compras"],
    estado: "En curso",
    fechaInicio: "2026-01-05",
    fechaFin: "2026-01-25",
    diasEjecutar: 20,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Lista_Proveedores.xlsx", url: "#" }],
    actividades: [
      { id: "a13", nombre: "Análisis contratos actuales", porcentaje: 100, completada: true },
      { id: "a14", nombre: "Negociación nuevos términos", porcentaje: 50, completada: false },
      { id: "a15", nombre: "Firma de contratos", porcentaje: 0, completada: false },
    ],
    avanceTotal: 50,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-28",
  },
  {
    id: "6",
    nombre: "Mantenimiento preventivo bombas estación norte",
    descripcion: "Mantenimiento programado de sistema de bombeo principal",
    areas: ["Mantenimiento"],
    estado: "Finalizado",
    fechaInicio: "2025-10-01",
    fechaFin: "2025-10-15",
    diasEjecutar: 15,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Operaciones"],
    documentos: [{ nombre: "Manual_Bombas.pdf", url: "#" }],
    actividades: [
      { id: "a16", nombre: "Inspección visual", porcentaje: 100, completada: true },
      { id: "a17", nombre: "Cambio de sellos", porcentaje: 100, completada: true },
      { id: "a18", nombre: "Pruebas de funcionamiento", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-09-20",
  },
  {
    id: "7",
    nombre: "Visita comunidad Las Vertientes",
    descripcion: "Reunión con líderes comunitarios para socialización de proyecto",
    areas: ["Comunidades"],
    estado: "En curso",
    fechaInicio: "2026-01-10",
    fechaFin: "2026-01-20",
    diasEjecutar: 10,
    prioridad: "Media",
    requiereApoyo: true,
    areasApoyo: ["Medio Ambiente", "Seguridad"],
    documentos: [],
    actividades: [
      { id: "a19", nombre: "Coordinación con líderes", porcentaje: 100, completada: true },
      { id: "a20", nombre: "Preparación material informativo", porcentaje: 80, completada: false },
      { id: "a21", nombre: "Ejecución de visita", porcentaje: 0, completada: false },
    ],
    avanceTotal: 60,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-02",
  },
  {
    id: "8",
    nombre: "Implementación sistema monitoreo ambiental",
    descripcion: "Instalación de sensores para monitoreo de calidad del aire y agua",
    areas: ["Medio Ambiente"],
    estado: "Finalizado",
    fechaInicio: "2025-09-01",
    fechaFin: "2025-10-30",
    diasEjecutar: 60,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Mantenimiento", "Operaciones"],
    documentos: [
      { nombre: "Especificaciones_Sensores.pdf", url: "#" },
      { nombre: "Plano_Ubicaciones.dwg", url: "#" },
    ],
    actividades: [
      { id: "a22", nombre: "Adquisición equipos", porcentaje: 100, completada: true },
      { id: "a23", nombre: "Instalación en campo", porcentaje: 100, completada: true },
      { id: "a24", nombre: "Calibración y pruebas", porcentaje: 100, completada: true },
      { id: "a25", nombre: "Capacitación operadores", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-08-15",
  },
  {
    id: "9",
    nombre: "Actualización procedimientos de calidad",
    descripcion: "Revisión y actualización de procedimientos ISO 9001",
    areas: ["Calidad"],
    estado: "En curso",
    fechaInicio: "2026-01-02",
    fechaFin: "2026-02-15",
    diasEjecutar: 45,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "ISO_9001_Checklist.pdf", url: "#" }],
    actividades: [
      { id: "a26", nombre: "Análisis de brechas", porcentaje: 100, completada: true },
      { id: "a27", nombre: "Redacción nuevos procedimientos", porcentaje: 30, completada: false },
      { id: "a28", nombre: "Validación con áreas", porcentaje: 0, completada: false },
      { id: "a29", nombre: "Publicación y difusión", porcentaje: 0, completada: false },
    ],
    avanceTotal: 33,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-20",
  },
  {
    id: "10",
    nombre: "Inspección ducto sector montaña",
    descripcion: "Inspección técnica del tramo de ducto en zona de alta montaña",
    areas: ["Operaciones"],
    estado: "Planificado",
    fechaInicio: "2026-02-15",
    fechaFin: "2026-03-15",
    diasEjecutar: 30,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Seguridad", "Mantenimiento"],
    documentos: [],
    actividades: [
      { id: "a30", nombre: "Planificación logística", porcentaje: 0, completada: false },
      { id: "a31", nombre: "Inspección visual", porcentaje: 0, completada: false },
      { id: "a32", nombre: "Análisis de integridad", porcentaje: 0, completada: false },
      { id: "a33", nombre: "Informe técnico", porcentaje: 0, completada: false },
    ],
    avanceTotal: 0,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-10",
  },
  {
    id: "11",
    nombre: "Compra EPP año 2026",
    descripcion: "Adquisición de equipos de protección personal para el año",
    areas: ["Compras", "Seguridad"],
    estado: "En curso",
    fechaInicio: "2026-01-01",
    fechaFin: "2026-01-31",
    diasEjecutar: 30,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Cotizaciones_EPP.xlsx", url: "#" }],
    actividades: [
      { id: "a34", nombre: "Solicitud de cotizaciones", porcentaje: 100, completada: true },
      { id: "a35", nombre: "Evaluación proveedores", porcentaje: 100, completada: true },
      { id: "a36", nombre: "Orden de compra", porcentaje: 50, completada: false },
      { id: "a37", nombre: "Recepción y distribución", porcentaje: 0, completada: false },
    ],
    avanceTotal: 63,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-15",
  },
  {
    id: "12",
    nombre: "Simulacro evacuación terminal marítimo",
    descripcion: "Ejercicio de evacuación general en instalaciones portuarias",
    areas: ["Seguridad"],
    estado: "Finalizado",
    fechaInicio: "2025-11-15",
    fechaFin: "2025-11-20",
    diasEjecutar: 5,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Operaciones", "Comunidades"],
    documentos: [{ nombre: "Plan_Simulacro.pdf", url: "#" }, { nombre: "Informe_Resultados.pdf", url: "#" }],
    actividades: [
      { id: "a38", nombre: "Planificación del ejercicio", porcentaje: 100, completada: true },
      { id: "a39", nombre: "Comunicación a participantes", porcentaje: 100, completada: true },
      { id: "a40", nombre: "Ejecución del simulacro", porcentaje: 100, completada: true },
      { id: "a41", nombre: "Evaluación y lecciones aprendidas", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-11-01",
  },
  {
    id: "13",
    nombre: "Renovación permisos ambientales",
    descripcion: "Trámite de renovación de permisos ante autoridad ambiental",
    areas: ["Legal", "Medio Ambiente"],
    estado: "En curso",
    fechaInicio: "2026-01-05",
    fechaFin: "2026-03-31",
    diasEjecutar: 85,
    prioridad: "Alta",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Expediente_Ambiental.pdf", url: "#" }],
    actividades: [
      { id: "a42", nombre: "Recopilación documentación", porcentaje: 100, completada: true },
      { id: "a43", nombre: "Presentación solicitud", porcentaje: 100, completada: true },
      { id: "a44", nombre: "Seguimiento trámite", porcentaje: 20, completada: false },
      { id: "a45", nombre: "Obtención resolución", porcentaje: 0, completada: false },
    ],
    avanceTotal: 55,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-20",
  },
  {
    id: "14",
    nombre: "Calibración instrumentos medición",
    descripcion: "Calibración anual de instrumentos de medición de flujo y presión",
    areas: ["Calidad", "Operaciones"],
    estado: "Finalizado",
    fechaInicio: "2025-12-01",
    fechaFin: "2025-12-20",
    diasEjecutar: 20,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Certificados_Calibracion.pdf", url: "#" }],
    actividades: [
      { id: "a46", nombre: "Identificación instrumentos", porcentaje: 100, completada: true },
      { id: "a47", nombre: "Calibración en laboratorio", porcentaje: 100, completada: true },
      { id: "a48", nombre: "Actualización registros", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-11-15",
  },
  {
    id: "15",
    nombre: "Programa de voluntariado corporativo",
    descripcion: "Organización de actividades de voluntariado con comunidades aledañas",
    areas: ["Comunidades"],
    estado: "Planificado",
    fechaInicio: "2026-03-01",
    fechaFin: "2026-03-15",
    diasEjecutar: 15,
    prioridad: "Baja",
    requiereApoyo: true,
    areasApoyo: ["Seguridad"],
    documentos: [],
    actividades: [
      { id: "a49", nombre: "Definición de actividades", porcentaje: 0, completada: false },
      { id: "a50", nombre: "Convocatoria voluntarios", porcentaje: 0, completada: false },
      { id: "a51", nombre: "Ejecución jornada", porcentaje: 0, completada: false },
    ],
    avanceTotal: 0,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-05",
  },
  {
    id: "16",
    nombre: "Mantenimiento correctivo válvula estación sur",
    descripcion: "Reparación urgente de válvula de control en estación sur",
    areas: ["Mantenimiento"],
    estado: "Finalizado",
    fechaInicio: "2025-12-10",
    fechaFin: "2025-12-12",
    diasEjecutar: 3,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Operaciones", "Seguridad"],
    documentos: [{ nombre: "Orden_Trabajo.pdf", url: "#" }],
    actividades: [
      { id: "a52", nombre: "Diagnóstico de falla", porcentaje: 100, completada: true },
      { id: "a53", nombre: "Adquisición repuestos", porcentaje: 100, completada: true },
      { id: "a54", nombre: "Reparación en campo", porcentaje: 100, completada: true },
      { id: "a55", nombre: "Prueba de funcionamiento", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-10",
  },
  {
    id: "17",
    nombre: "Evaluación desempeño proveedores",
    descripcion: "Evaluación semestral del desempeño de proveedores estratégicos",
    areas: ["Compras"],
    estado: "Finalizado",
    fechaInicio: "2025-12-01",
    fechaFin: "2025-12-15",
    diasEjecutar: 15,
    prioridad: "Media",
    requiereApoyo: true,
    areasApoyo: ["Calidad"],
    documentos: [{ nombre: "Matriz_Evaluacion.xlsx", url: "#" }],
    actividades: [
      { id: "a56", nombre: "Recopilación de indicadores", porcentaje: 100, completada: true },
      { id: "a57", nombre: "Análisis de resultados", porcentaje: 100, completada: true },
      { id: "a58", nombre: "Comunicación a proveedores", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-11-20",
  },
  {
    id: "18",
    nombre: "Inspección de seguridad instalaciones",
    descripcion: "Inspección trimestral de condiciones de seguridad en todas las instalaciones",
    areas: ["Seguridad"],
    estado: "Planificado",
    fechaInicio: "2026-02-01",
    fechaFin: "2026-02-15",
    diasEjecutar: 15,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [],
    actividades: [
      { id: "a59", nombre: "Preparación checklist", porcentaje: 0, completada: false },
      { id: "a60", nombre: "Inspección en campo", porcentaje: 0, completada: false },
      { id: "a61", nombre: "Informe de hallazgos", porcentaje: 0, completada: false },
    ],
    avanceTotal: 0,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-10",
  },
  {
    id: "19",
    nombre: "Actualización matriz de riesgos operacionales",
    descripcion: "Revisión anual de la matriz de identificación de peligros y evaluación de riesgos",
    areas: ["Seguridad", "Operaciones"],
    estado: "En curso",
    fechaInicio: "2026-01-08",
    fechaFin: "2026-01-28",
    diasEjecutar: 20,
    prioridad: "Alta",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Matriz_IPER_2025.xlsx", url: "#" }],
    actividades: [
      { id: "a62", nombre: "Revisión matriz actual", porcentaje: 100, completada: true },
      { id: "a63", nombre: "Identificación nuevos riesgos", porcentaje: 70, completada: false },
      { id: "a64", nombre: "Definición controles", porcentaje: 0, completada: false },
      { id: "a65", nombre: "Aprobación gerencial", porcentaje: 0, completada: false },
    ],
    avanceTotal: 43,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-05",
  },
  {
    id: "20",
    nombre: "Taller ambiental con comunidades",
    descripcion: "Taller de educación ambiental con escuelas de comunidades cercanas",
    areas: ["Medio Ambiente", "Comunidades"],
    estado: "Planificado",
    fechaInicio: "2026-03-10",
    fechaFin: "2026-03-12",
    diasEjecutar: 3,
    prioridad: "Baja",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [],
    actividades: [
      { id: "a66", nombre: "Coordinación con escuelas", porcentaje: 0, completada: false },
      { id: "a67", nombre: "Preparación material didáctico", porcentaje: 0, completada: false },
      { id: "a68", nombre: "Ejecución talleres", porcentaje: 0, completada: false },
    ],
    avanceTotal: 0,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-12",
  },
  {
    id: "21",
    nombre: "Mantenimiento preventivo sistema SCADA",
    descripcion: "Mantenimiento programado del sistema de control y adquisición de datos",
    areas: ["Mantenimiento", "Operaciones"],
    estado: "Finalizado",
    fechaInicio: "2025-11-01",
    fechaFin: "2025-11-10",
    diasEjecutar: 10,
    prioridad: "Alta",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Reporte_Mantenimiento.pdf", url: "#" }],
    actividades: [
      { id: "a69", nombre: "Backup de configuraciones", porcentaje: 100, completada: true },
      { id: "a70", nombre: "Actualización de software", porcentaje: 100, completada: true },
      { id: "a71", nombre: "Verificación de comunicaciones", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-10-20",
  },
  {
    id: "22",
    nombre: "Revisión pólizas de seguro",
    descripcion: "Análisis y renovación de pólizas de seguros corporativos",
    areas: ["Legal"],
    estado: "En curso",
    fechaInicio: "2026-01-02",
    fechaFin: "2026-01-30",
    diasEjecutar: 28,
    prioridad: "Media",
    requiereApoyo: true,
    areasApoyo: ["Compras"],
    documentos: [{ nombre: "Polizas_Vigentes.pdf", url: "#" }],
    actividades: [
      { id: "a72", nombre: "Análisis coberturas actuales", porcentaje: 100, completada: true },
      { id: "a73", nombre: "Solicitud de cotizaciones", porcentaje: 100, completada: true },
      { id: "a74", nombre: "Negociación con aseguradoras", porcentaje: 40, completada: false },
      { id: "a75", nombre: "Firma de pólizas", porcentaje: 0, completada: false },
    ],
    avanceTotal: 60,
    creadoPor: "Admin",
    fechaCreacion: "2025-12-28",
  },
  {
    id: "23",
    nombre: "Monitoreo de flora y fauna",
    descripcion: "Estudio de monitoreo de biodiversidad en área de influencia del ducto",
    areas: ["Medio Ambiente"],
    estado: "Finalizado",
    fechaInicio: "2025-10-15",
    fechaFin: "2025-11-30",
    diasEjecutar: 45,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Informe_Biodiversidad.pdf", url: "#" }],
    actividades: [
      { id: "a76", nombre: "Trabajo de campo", porcentaje: 100, completada: true },
      { id: "a77", nombre: "Análisis de muestras", porcentaje: 100, completada: true },
      { id: "a78", nombre: "Elaboración de informe", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-10-01",
  },
  {
    id: "24",
    nombre: "Certificación ISO 14001",
    descripcion: "Proceso de recertificación del sistema de gestión ambiental",
    areas: ["Calidad", "Medio Ambiente"],
    estado: "Planificado",
    fechaInicio: "2026-04-01",
    fechaFin: "2026-06-30",
    diasEjecutar: 90,
    prioridad: "Alta",
    requiereApoyo: true,
    areasApoyo: ["Legal"],
    documentos: [],
    actividades: [
      { id: "a79", nombre: "Auditoría interna", porcentaje: 0, completada: false },
      { id: "a80", nombre: "Cierre de no conformidades", porcentaje: 0, completada: false },
      { id: "a81", nombre: "Auditoría de certificación", porcentaje: 0, completada: false },
    ],
    avanceTotal: 0,
    creadoPor: "Admin",
    fechaCreacion: "2026-01-15",
  },
  {
    id: "25",
    nombre: "Inventario de equipos críticos",
    descripcion: "Actualización del inventario de equipos críticos para operación",
    areas: ["Operaciones", "Mantenimiento"],
    estado: "Finalizado",
    fechaInicio: "2025-12-01",
    fechaFin: "2025-12-20",
    diasEjecutar: 20,
    prioridad: "Media",
    requiereApoyo: false,
    areasApoyo: [],
    documentos: [{ nombre: "Inventario_2025.xlsx", url: "#" }],
    actividades: [
      { id: "a82", nombre: "Levantamiento en campo", porcentaje: 100, completada: true },
      { id: "a83", nombre: "Actualización base de datos", porcentaje: 100, completada: true },
      { id: "a84", nombre: "Validación con áreas", porcentaje: 100, completada: true },
    ],
    avanceTotal: 100,
    creadoPor: "Admin",
    fechaCreacion: "2025-11-20",
  },
]
